# Generated by Django 5.1.1 on 2024-09-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbo_clash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turbogame',
            name='flips_required',
            field=models.IntegerField(default=4),
        ),
    ]
