# Generated by Django 5.1.1 on 2024-09-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbo_clash', '0002_turbogame_flips_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='turbogame',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='turbogame',
            name='last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
