# Generated by Django 5.1.1 on 2024-09-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbo_clash', '0003_turbogame_current_round_turbogame_last_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='turbogame',
            name='round_played',
            field=models.IntegerField(default=0),
        ),
    ]
