# Generated by Django 5.1.1 on 2024-09-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legend_hunt', '0002_gameresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='joker_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='land_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='legend_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='real_estate_count',
            field=models.IntegerField(default=0),
        ),
    ]
