# Generated by Django 5.1.1 on 2024-09-20 12:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MileCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('card_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('card_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_1', to='mile_master.milecard')),
                ('card_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_2', to='mile_master.milecard')),
                ('card_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_3', to='mile_master.milecard')),
                ('card_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_4', to='mile_master.milecard')),
            ],
        ),
    ]
