# Generated by Django 5.1.1 on 2024-09-20 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mile_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_flip',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='round_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='card_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_1', to='mile_master.milecard'),
        ),
        migrations.AlterField(
            model_name='game',
            name='card_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_2', to='mile_master.milecard'),
        ),
        migrations.AlterField(
            model_name='game',
            name='card_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_3', to='mile_master.milecard'),
        ),
        migrations.AlterField(
            model_name='game',
            name='card_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_4', to='mile_master.milecard'),
        ),
    ]
