# Generated by Django 5.1.1 on 2024-09-20 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mile_master', '0002_game_current_flip_game_round_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='highest_score',
            new_name='total_score',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='updated_at',
        ),
    ]
