# Generated by Django 5.1.1 on 2024-09-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mile_master', '0004_alter_game_current_flip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_flip',
            field=models.IntegerField(default=1),
        ),
    ]
